const fs = require("fs");
const path = require("path");

/** 多义中文释义表（样例词书用） */
const MULTI = {
  abandon: ["放弃", "遗弃", "放纵"],
  ability: ["能力", "才能", "本领"],
  abroad: ["在国外", "到海外", "广为流传地"],
  absolute: ["绝对的", "完全的", "专制的"],
  absorb: ["吸收", "吸引", "使全神贯注"],
  abstract: ["抽象的", "摘要", "提取"],
  abundant: ["丰富的", "充裕的"],
  abuse: ["滥用", "虐待", "辱骂"],
  academic: ["学术的", "学院的", "纯理论的"],
  accelerate: ["加速", "促进"],
  accent: ["口音", "重音", "强调"],
  accept: ["接受", "认可", "承担"],
  access: ["通道", "使用权", "接近"],
  accident: ["事故", "意外", "碰巧"],
  accommodate: ["容纳", "为…提供住宿", "适应"],
  accompany: ["陪伴", "伴随", "伴奏"],
  accomplish: ["完成", "实现"],
  account: ["账户", "叙述", "解释"],
  accumulate: ["积累", "积聚"],
  accurate: ["准确的", "精确的"],
  accuse: ["指责", "控告"],
  achieve: ["达到", "完成", "取得"],
  acid: ["酸", "尖刻的"],
  acknowledge: ["承认", "告知收到", "致谢"],
  acquire: ["获得", "习得", "购得"],
  across: ["穿过", "在对面", "遍及"],
  act: ["行动", "表演", "法令"],
  adapt: ["适应", "改编"],
  addict: ["上瘾者", "对…入迷的人"],
  addition: ["增加", "加法", "附加物"],
  adequate: ["足够的", "适当的"],
  adjust: ["调整", "适应"],
  admire: ["钦佩", "欣赏"],
  admit: ["承认", "允许进入"],
  adopt: ["采纳", "收养"],
  adult: ["成年人", "成年的"],
  advance: ["前进", "提前", "进展"],
  advantage: ["优势", "好处"],
  adventure: ["冒险", "奇遇"],
  advertise: ["做广告", "宣传"],
  advice: ["建议", "忠告"],
  affair: ["事务", "风流韵事", "事件"],
  affect: ["影响", "感动"],
  afford: ["负担得起", "提供"],
  afraid: ["害怕的", "担心的"],
  agency: ["代理机构", "作用", "中介"],
  agenda: ["议程", "日程"],
  agent: ["代理人", "特工", "作用因素"],
  aggressive: ["侵略的", "有进取心的", "好斗的"],
  agree: ["同意", "一致", "商定"],
  agriculture: ["农业", "农学"],
  ahead: ["在前面", "提前", "领先"],
  aid: ["援助", "助手", "帮助"],
  aim: ["目标", "瞄准", "旨在"],
  alarm: ["警报", "惊恐", "闹钟"],
  album: ["相册", "专辑"],
  alcohol: ["酒精", "酒"],
  alert: ["警觉的", "警报", "提醒"],
  alike: ["相像的", "同样地"],
  alive: ["活着的", "有活力的"],
  abolish: ["废除", "取消"],
  abrupt: ["突然的", "唐突的"],
  absurd: ["荒谬的", "荒唐的"],
  abundance: ["丰富", "大量"],
  accessory: ["配件", "同谋", "附属物"],
  accord: ["协议", "一致", "给予"],
  acquaint: ["使熟悉", "使认识"],
  activate: ["激活", "使活动"],
  acute: ["严重的", "敏锐的", "急性的"],
  adhere: ["坚持", "粘附", "遵守"],
  adjacent: ["邻近的", "毗连的"],
  administer: ["管理", "实施", "给予（药物）"],
  adolescent: ["青少年", "青春期的"],
  adverse: ["不利的", "有害的"],
  advocate: ["提倡", "拥护者", "辩护"],
  aesthetic: ["美学的", "审美的"],
  affiliate: ["使隶属", "分支机构"],
  affirm: ["断言", "证实"],
  afflict: ["折磨", "使痛苦"],
  affluent: ["富裕的", "丰富的"],
  aggravate: ["加重", "激怒"],
  aggregate: ["总计", "聚合的", "合计"],
  agitate: ["煽动", "使焦虑", "剧烈摇动"],
  agreeable: ["令人愉快的", "同意的"],
  airborne: ["空运的", "空气传播的", "在空中的"],
  aisle: ["过道", "侧廊"],
  alien: ["陌生的", "外星的", "外国人"],
  allege: ["声称", "断言"],
  alleviate: ["减轻", "缓和"],
  allocate: ["分配", "划拨"],
  allot: ["分配", "拨给"],
  alloy: ["合金", "混合物"],
  ally: ["盟友", "同盟国", "联合"],
  alternate: ["交替的", "候补的", "轮流"],
  ambiguous: ["模棱两可的", "含糊的"],
  ambition: ["雄心", "抱负", "野心"],
  amend: ["修改", "改进"],
  amiable: ["和蔼的", "亲切的"],
  amid: ["在…之中", "在…中间"],
  ammunition: ["弹药", "攻击材料"],
  amplify: ["放大", "增强", "详述"],
  analogy: ["类比", "相似"],
  analyst: ["分析师", "化验员"],
  ancestor: ["祖先", "原种"],
  anchor: ["锚", "主播", "使固定"],
  anecdote: ["轶事", "趣闻"],
  angel: ["天使", "善人"],
  anniversary: ["周年纪念", "周年纪念日"],
  anonymous: ["匿名的", "无名的"],
  antagonist: ["对手", "反派", "拮抗剂"],
  anticipate: ["预期", "预料", "先于…行动"],
  antique: ["古董", "古老的"],
  anxiety: ["焦虑", "渴望"],
  apology: ["道歉", "辩解"],
  apparatus: ["器械", "机构", "仪器"],
  appeal: ["呼吁", "上诉", "吸引力"],
  appetite: ["食欲", "欲望"],
  aberrant: ["异常的", "偏离常规的"],
  abide: ["遵守", "容忍", "居住"],
  absorption: ["吸收", "专注"],
  accessible: ["可到达的", "易懂的", "易接近的"],
  accomplice: ["同谋", "帮凶"],
  accusation: ["指控", "谴责"],
  accustom: ["使习惯"],
  acquaintance: ["熟人", "相识", "了解"],
  acquisition: ["获得", "收购", "习得"],
  adaptability: ["适应性", "适应能力"],
  addiction: ["瘾", "沉溺"],
  adept: ["熟练的", "内行"],
  adjunct: ["附属物", "助手", "附加语"],
  admirable: ["令人钦佩的", "极好的"],
  admission: ["准许进入", "承认", "入场费"],
  adoption: ["采用", "收养"],
  adore: ["崇拜", "热爱"],
  adorn: ["装饰", "使增色"],
  advantageous: ["有利的", "有益的"],
  adversary: ["对手", "敌手"],
  affection: ["感情", "喜爱"],
  aftermath: ["后果", "余波"],
  agile: ["敏捷的", "灵活的"],
  agonize: ["痛苦挣扎", "焦虑不已"],
  ailment: ["小病", "微恙"],
  airy: ["通风的", "轻快的", "幻想的"],
  akin: ["类似的", "同族的"],
  alienate: ["疏远", "转让"],
};

const EX_ZH = {
  "They had to abandon the sinking ship.": "他们不得不放弃那艘正在下沉的船。",
  "She has the ability to learn quickly.": "她有快速学习的能力。",
  "He studied abroad for two years.": "他在国外学习了两年。",
};

const files = ["cet4-sample.json", "cet6-sample.json", "kaoyan-sample.json"];
const dir = path.join("src", "data");

for (const f of files) {
  const p = path.join(dir, f);
  const data = JSON.parse(fs.readFileSync(p, "utf8"));
  const out = data.map((w) => {
    const key = w.word.toLowerCase();
    const meanings = MULTI[key] || [
      w.meaning,
      ...(String(w.meaning).includes("；")
        ? String(w.meaning).split(/[；;]/).map((s) => s.trim())
        : []),
    ].filter((m, i, a) => m && a.indexOf(m) === i);

    const example =
      w.example ||
      w.examples?.[0] ||
      `Please learn how to use "${w.word}" in a sentence.`;
    const exampleZh =
      EX_ZH[example] ||
      (meanings[0] ? `这句话展示了 “${w.word}” 表示「${meanings[0]}」的用法。` : "");

    return {
      word: w.word,
      meaning: meanings[0],
      meanings,
      pos: w.pos,
      phonetic: w.phonetic,
      example,
      examples: [example],
      exampleTranslations: [exampleZh],
    };
  });
  fs.writeFileSync(p, JSON.stringify(out, null, 2) + "\n");
  console.log("updated", f, out.length);
}
